import { css } from "@emotion/css";

export const styles = {
  root: css({
    position: "relative",
    display: "flex",
    minHeight: "100vh",
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundSize: "cover",
    backgroundPosition: "center",
    boxSizing: "border-box",
    backgroundRepeat: "no-repeat",
    padding: "1rem",
    backgroundImage: `linear-gradient(rgba(16, 22, 34, 0.8) 0%, rgba(16, 22, 34, 1) 100%), url("https://lh3.googleusercontent.com/aida-public/AB6AXuANgdyy7imNSLu85WFC2Ltb-akOsY1tekQtuZPRQfuL9mMwRa2PAsjtHNzwYZdgIcT3z0y-v48LvNaysjpCJYyJhllwFkjicRbujTdxqSpIkTVQ6crwrnHOkrWruhiBOV-XDDnBoaf-X-WuQRH8TkGpJmxFRDrUt1Ve798eI8VyoG3otf_PgUKYdBwncf6Kq15gj9yplcYozfSdr--wWKC23wxKQnHTsHjiggm3GOMN5lt5WX0VgTPliWPRFg10f6avRWhlHp6iu4tF")`,
  }),
  container: css({
    width: "100%",
    maxWidth: "24rem",
    rowGap: "2rem",
    borderRadius: "0.75rem",
    backgroundColor: "rgba(16, 22, 34, 0.5)",
    padding: "1.5rem",
    backdropFilter: "blur(4px)",

    "@media (max-width:500px)": {
      maxWidth: "19rem",
    },
  }),
  iconContainer: css({
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: "1rem",
    display: "flex",
    height: "4rem",
    width: "4rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "9999px",
    backgroundColor: "#E50914",
    color: "white",
  }),
  loginTitle: css({
    whiteSpace: "nowrap",
    fontSize: "2.25rem",
  }),
  title: css({
    fontSize: "1.875rem",
    fontWeight: 900,
    lineHeight: "1.25",
    letterSpacing: "-0.015em",
    color: "white",

    "@sm": {
      fontSize: "2.25rem",
    },
  }),
  formGroup: css({
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
  }),
  labelWrapper: css({
    display: "flex",
    flexDirection: "column",
  }),
  labelTitle: css({
    paddingBottom: "0.5rem",
    margin: 0,
    fontSize: "1rem",
    fontWeight: 500,
    lineHeight: "normal",
    color: "#ffffff",
  }),
  inputWrapper: css({
    display: "flex",
    width: "100%",
    flex: 1,
    alignItems: "stretch",
    borderRadius: "0.5rem",
  }),
  inputIconLeft: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 0.5rem",
    boxSizing: "border-box",
    color: "rgb(156 163 175)",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderLeft: "1px solid rgba(255,255,255,0.2)",
    borderTop: "1px solid rgba(255,255,255,0.2)",
    borderBottom: "1px solid rgba(255,255,255,0.2)",
    borderRadius: "0.5rem 0 0 0.5rem",
  }),
  inputField: css({
    flex: 1,
    resize: "none",
    overflow: "hidden",
    padding: "1rem",
    fontSize: "1rem",
    fontWeight: 400,
    lineHeight: "normal",
    color: "#ffffff",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRight: "1px solid rgba(255,255,255,0.2)",
    borderLeft: "0.5px solid rgba(255,255,255,0.2)",
    borderTop: "1px solid rgba(255,255,255,0.2)",
    borderBottom: "1px solid rgba(255,255,255,0.2)",
    outline: "none",
    borderRadius: "0 0.5rem 0.5rem 0",

    "&::placeholder": {
      color: "rgb(156 163 175)",
    },

    "&:focus": {
      borderColor: "rgba(229, 9, 20, 0.8)",
      outline: "none",
      boxShadow: "none",
    },
  }),
  bottomContainer: css({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1rem",
  }),

  button: css({
    display: "flex",
    height: "3.5rem",
    width: "100%",
    cursor: "pointer",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "1rem",
    overflow: "hidden",
    borderRadius: "0.5rem",
    backgroundColor: "#E50914",
    fontSize: "1rem",
    fontWeight: 700,
    lineHeight: "1.5",
    letterSpacing: "0.025em",
    color: "#ffffff",
    transition: "background-color 0.2s ease",
    "&:hover": {
      backgroundColor: "rgba(229, 9, 20, 0.9)",
    },
  }),

  buttonText: css({
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  subtitle: css({
    marginTop: "0.5rem",
    fontSize: "1rem",
    fontWeight: 400,
    lineHeight: "1.5",
    color: "rgb(209 213 219)",
  }),
};
