import { css } from "@emotion/css";

export const styles = {
  leftSideContainer: css({
    flex: "1 0 0 ",
    background: "white",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: 24,
    gap: 32,
    boxSizing: "border-box",
  }),
  leftSideInfo: css({
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: 450,
    alignItems: "center",
    gap: 24,
  }),
  leftSideBudget: css({
    display: "flex",
    width: "100%",
    gap: 16,
    justifyContent: "space-between",
  }),
  leftSideTotalInfo: css({
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
  }),
  rightSideContainer: css({
    flex: "1 0 0 ",
    background: "white",
    display: "flex",
    justifyContent: "center",
    padding: 24,
    boxSizing: "border-box",
  }),
  expensesContainer: css({
    display: "flex",
    flexDirection: "column",
    gap: 16,
    maxHeight: "350px",
    overflowY: "auto",
  }),
  expenseInfo: css({
    width: "100%",
    padding: "12px 16px",
    background: "rgb(235,235,235)",
    display: "flex",
    justifyContent: "space-between",
    boxSizing: "border-box",
    alignItems: "center",
  }),
  expenseImage: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 48,
    height: 48,
  }),
  expenseText: css({
    display: "flex",
    flexDirection: "column",
    gap: 4,
    width: "100%",
    maxWidth: 150,
    overflow: "hidden",
  }),
  expenseStructure: css({
    display: "flex",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
  }),
  dashboardContainer: css({
    display: "flex",
    justifyContent: "center",
    gap: 16,
    height: "100%",
    width: "100%",
    padding: "48px",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "16px",
      flexDirection: "column",
      gap: 12,
    },

    "@media (max-width: 480px)": {
      padding: "8px",
      justifyContent: "flex-start",
    },
  }),
  select: css({
    height: 56,
  }),
};
